name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    # Step 1 : Clone git repository
    - uses: actions/checkout@v2

    # Step 2 : Set JDK
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    # Step 3 : Set up gradlew file
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Step 4: Run unit tests
    - name: Run unit tests
      run: ./gradlew test -x data:test

    # Step 5: Run instrumented tests
    - name: Run instrumented tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: ./gradlew connectedAndroidTest -x data:connectedAndroidTest

    # Step 6: Run build
    - name: Build with Gradle
      run: ./gradlew app:assemble
